FROM node:18.16.0
LABEL maintainer="jana.ru.sidorova@yandex.ru"
ENV NODE_ENV=development PORT=1083

RUN mkdir -p /usr/src/animal-service
WORKDIR /usr/src/animal-service

COPY ["package.json", "package-lock.json*", "./"]

RUN npm install

COPY . .

EXPOSE 1083

CMD [ "npm", "run", "start" ]
